// This file is auto-generated by setup-projects.js. Do not edit manually.

export interface Project {
  id: string;
  title: string;
  coverImage: string;
  images: string[];
}

export const projects: Project[] = [
  {
    "id": "michela-donnino",
    "title": "Michela Donnino",
    "coverImage": "/projects/michela donnino/DSC02414.jpg",
    "images": [
      "/projects/michela donnino/DSC02414.jpg",
      "/projects/michela donnino/DSC02437.jpg",
      "/projects/michela donnino/DSC02497.jpg",
      "/projects/michela donnino/DSC02539.jpg",
      "/projects/michela donnino/DSC02542.jpg",
      "/projects/michela donnino/DSC02645.jpg",
      "/projects/michela donnino/DSC02972.jpg",
      "/projects/michela donnino/DSC02993.jpg",
      "/projects/michela donnino/DSC02997.jpg"
    ]
  },
  {
    "id": "salvatore-manuele-iervolino",
    "title": "Salvatore",
    "coverImage": "/projects/Salvatore Manuele Iervolino/DSC07979.jpg",
    "images": [
      "/projects/Salvatore Manuele Iervolino/cover.jpg",
      "/projects/Salvatore Manuele Iervolino/DSC07979.jpg",
      "/projects/Salvatore Manuele Iervolino/DSC08016.jpg",
      "/projects/Salvatore Manuele Iervolino/DSC08067.jpg"
    ]
  },
  {
    "id": "austria",
    "title": "Austria",
    "coverImage": "/projects/austria/R0001844.jpg",
    "images": [
      "/projects/austria/R0001844.jpg",
      "/projects/austria/R0001851.jpg",
      "/projects/austria/R0001922.jpg",
      "/projects/austria/R0001942.jpg",
      "/projects/austria/R0001946.jpg",
      "/projects/austria/R0001949.jpg",
      "/projects/austria/R0001983.jpg"
    ]
  },
  {
    "id": "austria-2",
    "title": "Austria 2",
    "coverImage": "/projects/austria 2/R0002100.jpg",
    "images": [
      "/projects/austria 2/R0001988.jpg",
      "/projects/austria 2/R0002000-2.jpg",
      "/projects/austria 2/R0002003.jpg",
      "/projects/austria 2/R0002012.jpg",
      "/projects/austria 2/R0002015.jpg",
      "/projects/austria 2/R0002021.jpg",
      "/projects/austria 2/R0002066.jpg",
      "/projects/austria 2/R0002084.jpg",
      "/projects/austria 2/R0002100.jpg"
    ]
  },
  {
    "id": "snaps",
    "title": "Snaps",
    "coverImage": "/projects/snaps/R0004503.jpg",
    "images": [
      "/projects/snaps/R0004503.jpg",
      "/projects/snaps/R0004538.jpg",
      "/projects/snaps/R0004551.jpg",
      "/projects/snaps/R0004578.jpg",
      "/projects/snaps/R0004638.jpg"
    ]
  },
  {
    "id": "ferrigno",
    "title": "Ferrigno",
    "coverImage": "/projects/ferrigno/DSC00062.jpg",
    "images": [
      "/projects/ferrigno/DSC00062.jpg",
      "/projects/ferrigno/DSC00112.jpg",
      "/projects/ferrigno/DSC00122.jpg",
      "/projects/ferrigno/DSC00413.jpg",
      "/projects/ferrigno/DSC00466.jpg",
      "/projects/ferrigno/DSC00480.jpg",
      "/projects/ferrigno/DSC00576.jpg",
      "/projects/ferrigno/DSC00590.jpg"
    ]
  },
  {
    "id": "zi-rosa",
    "title": "Zi Rosa",
    "coverImage": "/projects/Zi rosa/DSC02601.jpg",
    "images": [
      "/projects/Zi rosa/DSC02581.jpg",
      "/projects/Zi rosa/DSC02594.jpg",
      "/projects/Zi rosa/DSC02596.jpg",
      "/projects/Zi rosa/DSC02601.jpg",
      "/projects/Zi rosa/DSC02603.jpg",
      "/projects/Zi rosa/DSC02610.jpg",
      "/projects/Zi rosa/DSC02614.jpg"
    ]
  },
  {
    "id": "ariete",
    "title": "Ariete",
    "coverImage": "/projects/ariete/DSC01951-2.jpg",
    "images": [
      "/projects/ariete/DSC01951-2.jpg",
      "/projects/ariete/DSC01951.jpg",
      "/projects/ariete/DSC02082-2.jpg",
      "/projects/ariete/DSC02082.jpg",
      "/projects/ariete/DSC02126.jpg",
      "/projects/ariete/DSC02155-2.jpg",
      "/projects/ariete/DSC02155.jpg",
      "/projects/ariete/DSC02196.jpg",
      "/projects/ariete/DSC02255.jpg"
    ]
  },
  {
    "id": "onemorepizza",
    "title": "One More Pizza",
    "coverImage": "/projects/onemorepizza/DSC03689.jpg",
    "images": [
      "/projects/onemorepizza/DSC03055.jpg",
      "/projects/onemorepizza/DSC03167.jpg",
      "/projects/onemorepizza/DSC03226.jpg",
      "/projects/onemorepizza/DSC03236.jpg",
      "/projects/onemorepizza/DSC03282.jpg",
      "/projects/onemorepizza/DSC03354.jpg",
      "/projects/onemorepizza/DSC03360.jpg",
      "/projects/onemorepizza/DSC03657.jpg",
      "/projects/onemorepizza/DSC03658.jpg",
      "/projects/onemorepizza/DSC03663.jpg",
      "/projects/onemorepizza/DSC03689.jpg"
    ]
  },
  {
    "id": "riva",
    "title": "Riva",
    "coverImage": "/projects/RIVA/DSC06751.jpg",
    "images": [
      "/projects/RIVA/DSC06751.jpg",
      "/projects/RIVA/DSC06761.jpg",
      "/projects/RIVA/DSC06777.jpg",
      "/projects/RIVA/DSC06902.jpg",
      "/projects/RIVA/DSC06914.jpg",
      "/projects/RIVA/DSC06921.jpg",
      "/projects/RIVA/DSC06949.jpg",
      "/projects/RIVA/DSC06963.jpg",
      "/projects/RIVA/DSC06974.jpg",
      "/projects/RIVA/DSC06990.jpg"
    ]
  },
  {
    "id": "ugocrepa",
    "title": "Ugo Crepa",
    "coverImage": "/projects/ugocrepa/DSC08741.jpg",
    "images": [
      "/projects/ugocrepa/DSC08046.jpg",
      "/projects/ugocrepa/DSC08172.jpg",
      "/projects/ugocrepa/DSC08187.jpg",
      "/projects/ugocrepa/DSC08217.jpg",
      "/projects/ugocrepa/DSC08741.jpg"
    ]
  },
  {
    "id": "chyky",
    "title": "Chyky",
    "coverImage": "/projects/chyky/COVERDEFINITIVAUFFICIALEFIRMATAHEREWEGO2.jpg",
    "images": [
      "/projects/chyky/COVERDEFINITIVAUFFICIALEFIRMATAHEREWEGO2.jpg",
      "/projects/chyky/DSC00198.jpg",
      "/projects/chyky/DSC01732.jpg",
      "/projects/chyky/DSC01739.jpg",
      "/projects/chyky/DSC01792.jpg",
      "/projects/chyky/DSC01843.jpg",
      "/projects/chyky/DSC01865-2.jpg",
      "/projects/chyky/TRACKLISTNAPLESBABYUFFICIALEDEFINTIVAFIRMATAHEREWEGO.jpg"
    ]
  },
  {
    "id": "indiemen",
    "title": "Indiemen",
    "coverImage": "/projects/indiemen/DSC07262.jpg",
    "images": [
      "/projects/indiemen/DSC00432.jpg",
      "/projects/indiemen/DSC00452.jpg",
      "/projects/indiemen/DSC00479.jpg",
      "/projects/indiemen/DSC00486.jpg",
      "/projects/indiemen/DSC01951.jpg",
      "/projects/indiemen/DSC07262.jpg",
      "/projects/indiemen/DSC07265.jpg",
      "/projects/indiemen/DSC08969.jpg",
      "/projects/indiemen/DSC09532.jpg",
      "/projects/indiemen/DSC09744.jpg"
    ]
  }
];
